AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NestJS Application with Fastify on Lambda
Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: nodejs18.x
Resources:
  NestJsApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: dist/lambda.handler
      Environment:
        Variables:
          NODE_ENV: production
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: ApiGateway
            Path: /{proxy+}
            Method: ANY
        RootPath:
          Type: HttpApi
          Properties:
            ApiId:
              Ref: ApiGateway
            Path: /
            Method: ANY
    Metadata:
      SamResourceId: NestJsApi
  ApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
        - '*'
        AllowHeaders:
        - '*'
        AllowMethods:
        - '*'
    Metadata:
      SamResourceId: ApiGateway
Outputs:
  NestJsApiEndpoint:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev
  NestJsFunction:
    Description: Lambda Function ARN
    Value:
      Fn::GetAtt:
      - NestJsApi
      - Arn
